#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libblockdev
Version  : 3.0.1
Release  : 62
URL      : https://github.com/storaged-project/libblockdev/releases/download/3.0-1/libblockdev-3.0.tar.gz
Source0  : https://github.com/storaged-project/libblockdev/releases/download/3.0-1/libblockdev-3.0.tar.gz
Summary  : A library for low-level manipulation with block devices
Group    : Development/Tools
License  : LGPL-2.1 LGPL-2.1+
Requires: libblockdev-bin = %{version}-%{release}
Requires: libblockdev-data = %{version}-%{release}
Requires: libblockdev-lib = %{version}-%{release}
Requires: libblockdev-license = %{version}-%{release}
Requires: libblockdev-python = %{version}-%{release}
Requires: libblockdev-python3 = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : glibc-bin
BuildRequires : gobject-introspection-dev
BuildRequires : keyutils-dev
BuildRequires : nss-dev
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(bytesize)
BuildRequires : pkgconfig(devmapper)
BuildRequires : pkgconfig(e2p)
BuildRequires : pkgconfig(ext2fs)
BuildRequires : pkgconfig(fdisk)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libcryptsetup)
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libndctl)
BuildRequires : pkgconfig(libnvme)
BuildRequires : pkgconfig(libparted)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(uuid)
BuildRequires : volume_key-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The libblockdev is a C library with GObject introspection support that can be
used for doing low-level operations with block devices like setting up LVM,
BTRFS, LUKS or MD RAID. The library uses plugins (LVM, BTRFS,...) and serves as
a thin wrapper around its plugins' functionality. All the plugins, however, can
be used as standalone libraries. One of the core principles of libblockdev is
that it is stateless from the storage configuration's perspective (e.g. it has
no information about VGs when creating an LV).

%package bin
Summary: bin components for the libblockdev package.
Group: Binaries
Requires: libblockdev-data = %{version}-%{release}
Requires: libblockdev-license = %{version}-%{release}

%description bin
bin components for the libblockdev package.


%package data
Summary: data components for the libblockdev package.
Group: Data

%description data
data components for the libblockdev package.


%package dev
Summary: dev components for the libblockdev package.
Group: Development
Requires: libblockdev-lib = %{version}-%{release}
Requires: libblockdev-bin = %{version}-%{release}
Requires: libblockdev-data = %{version}-%{release}
Provides: libblockdev-devel = %{version}-%{release}
Requires: libblockdev = %{version}-%{release}

%description dev
dev components for the libblockdev package.


%package lib
Summary: lib components for the libblockdev package.
Group: Libraries
Requires: libblockdev-data = %{version}-%{release}
Requires: libblockdev-license = %{version}-%{release}

%description lib
lib components for the libblockdev package.


%package license
Summary: license components for the libblockdev package.
Group: Default

%description license
license components for the libblockdev package.


%package python
Summary: python components for the libblockdev package.
Group: Default
Requires: libblockdev-python3 = %{version}-%{release}

%description python
python components for the libblockdev package.


%package python3
Summary: python3 components for the libblockdev package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libblockdev package.


%prep
%setup -q -n libblockdev-3.0
cd %{_builddir}/libblockdev-3.0
pushd ..
cp -a libblockdev-3.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1687978761
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1687978761
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libblockdev
cp %{_builddir}/libblockdev-3.0/LICENSE %{buildroot}/usr/share/package-licenses/libblockdev/507ba5f4949dedff9e01b4d5b64b365fdc7d4d04 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/lvm-cache-stats
/V3/usr/bin/vfat-resize
/usr/bin/lvm-cache-stats
/usr/bin/vfat-resize

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/BlockDev-3.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/blockdev/blockdev.h
/usr/include/blockdev/btrfs.h
/usr/include/blockdev/crypto.h
/usr/include/blockdev/dbus.h
/usr/include/blockdev/dev_utils.h
/usr/include/blockdev/dm.h
/usr/include/blockdev/exec.h
/usr/include/blockdev/extra_arg.h
/usr/include/blockdev/fs.h
/usr/include/blockdev/fs/btrfs.h
/usr/include/blockdev/fs/exfat.h
/usr/include/blockdev/fs/ext.h
/usr/include/blockdev/fs/f2fs.h
/usr/include/blockdev/fs/generic.h
/usr/include/blockdev/fs/mount.h
/usr/include/blockdev/fs/nilfs.h
/usr/include/blockdev/fs/ntfs.h
/usr/include/blockdev/fs/udf.h
/usr/include/blockdev/fs/vfat.h
/usr/include/blockdev/fs/xfs.h
/usr/include/blockdev/logging.h
/usr/include/blockdev/loop.h
/usr/include/blockdev/lvm.h
/usr/include/blockdev/mdraid.h
/usr/include/blockdev/module.h
/usr/include/blockdev/mpath.h
/usr/include/blockdev/nvdimm.h
/usr/include/blockdev/nvme.h
/usr/include/blockdev/part.h
/usr/include/blockdev/plugins.h
/usr/include/blockdev/sizes.h
/usr/include/blockdev/swap.h
/usr/include/blockdev/utils.h
/usr/lib64/libbd_btrfs.so
/usr/lib64/libbd_crypto.so
/usr/lib64/libbd_dm.so
/usr/lib64/libbd_fs.so
/usr/lib64/libbd_loop.so
/usr/lib64/libbd_lvm-dbus.so
/usr/lib64/libbd_lvm.so
/usr/lib64/libbd_mdraid.so
/usr/lib64/libbd_mpath.so
/usr/lib64/libbd_nvdimm.so
/usr/lib64/libbd_nvme.so
/usr/lib64/libbd_part.so
/usr/lib64/libbd_swap.so
/usr/lib64/libbd_utils.so
/usr/lib64/libblockdev.so
/usr/lib64/pkgconfig/blockdev-utils.pc
/usr/lib64/pkgconfig/blockdev.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libbd_btrfs.so.3.0.0
/V3/usr/lib64/libbd_crypto.so.3.0.0
/V3/usr/lib64/libbd_dm.so.3.0.0
/V3/usr/lib64/libbd_fs.so.3.0.0
/V3/usr/lib64/libbd_loop.so.3.0.0
/V3/usr/lib64/libbd_lvm-dbus.so.3.0.0
/V3/usr/lib64/libbd_lvm.so.3.0.0
/V3/usr/lib64/libbd_mdraid.so.3.0.0
/V3/usr/lib64/libbd_mpath.so.3.0.0
/V3/usr/lib64/libbd_nvdimm.so.3.0.0
/V3/usr/lib64/libbd_nvme.so.3.0.0
/V3/usr/lib64/libbd_part.so.3.0.0
/V3/usr/lib64/libbd_swap.so.3.0.0
/V3/usr/lib64/libbd_utils.so.3.0.0
/V3/usr/lib64/libblockdev.so.3.0.0
/usr/lib64/libbd_btrfs.so.3
/usr/lib64/libbd_btrfs.so.3.0.0
/usr/lib64/libbd_crypto.so.3
/usr/lib64/libbd_crypto.so.3.0.0
/usr/lib64/libbd_dm.so.3
/usr/lib64/libbd_dm.so.3.0.0
/usr/lib64/libbd_fs.so.3
/usr/lib64/libbd_fs.so.3.0.0
/usr/lib64/libbd_loop.so.3
/usr/lib64/libbd_loop.so.3.0.0
/usr/lib64/libbd_lvm-dbus.so.3
/usr/lib64/libbd_lvm-dbus.so.3.0.0
/usr/lib64/libbd_lvm.so.3
/usr/lib64/libbd_lvm.so.3.0.0
/usr/lib64/libbd_mdraid.so.3
/usr/lib64/libbd_mdraid.so.3.0.0
/usr/lib64/libbd_mpath.so.3
/usr/lib64/libbd_mpath.so.3.0.0
/usr/lib64/libbd_nvdimm.so.3
/usr/lib64/libbd_nvdimm.so.3.0.0
/usr/lib64/libbd_nvme.so.3
/usr/lib64/libbd_nvme.so.3.0.0
/usr/lib64/libbd_part.so.3
/usr/lib64/libbd_part.so.3.0.0
/usr/lib64/libbd_swap.so.3
/usr/lib64/libbd_swap.so.3.0.0
/usr/lib64/libbd_utils.so.3
/usr/lib64/libbd_utils.so.3.0.0
/usr/lib64/libblockdev.so.3
/usr/lib64/libblockdev.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libblockdev/507ba5f4949dedff9e01b4d5b64b365fdc7d4d04

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
